[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["oidc_auth/"]

[project]
name = "drf-jwt-multi-auth"
version = "1.0.0"
authors = [
  { name="Simon O. Tveit", email="simon.tveit@sikt.no"},
]
description = "Package for authenticating JWT tokens from multiple issuers"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "MIT"
license-files = ["LICEN[CS]E*"]
dependencies = [
    "authlib>=0.15.0",
    "cryptography>=2.6",
    "django>=4.2.0",
    "djangorestframework>=3.12.0",
    "requests>=2.20.0",
    "pyjwt>=2.6.0",
]

[project.urls]
Homepage = "https://github.com/Uninett/drf-oidc-auth"
Issues = "https://github.com/Uninett/drf-oidc-auth/issues"
