name: Run tests

on:
  pull_request:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - run: uv sync

      - name: Run tests
        env:
          DJANGO_SETTINGS_MODULE: tests.settings
          PYTHONPATH: ${{ github.workspace }}
        run: uv run python -m django test
